# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Import Certs'
  lane :certs do |options|
    create_keychain(
      name: 'CI_Build',
      default_keychain: true,
      password: ENV['MATCH_PASSWORD'],
      unlock: true,
      timeout: 3600
    )
    match(
      git_basic_authorization: Base64.strict_encode64("#{ENV['GITHUB_USER']}:#{ENV['GITHUB_TOKEN']}"),
      type: 'development',
      keychain_name: 'CI_Build',
      keychain_password: ENV['MATCH_PASSWORD'],
      readonly: true
    )
  end
  desc 'Build'
  lane :build do |options|
    build_ios_app(
      configuration: options[:release] == true ? 'Release' : 'Debug',
      output_directory: 'build',
      export_method: options[:release] == true ? 'app-store' : 'development',
      scheme: 'DominionCompanion',
      project: 'DominionCompanion.xcodeproj',
      clean: true
    )
  end

  desc 'Unit Tests'
  lane :test do
    scan(
      scheme: 'DominionCompanion',
      output_directory: 'reports',
      output_types: 'junit',
      output_files: 'junit.xml',
      clean: true,
      code_coverage: true
    )
  end

  desc "Code Coverage"
  lane :coverage do |options|
    slather(
      proj: 'DominionCompanion.xcodeproj',
      scheme: 'DominionCompanion',
      output_directory: 'reports/coverage',
      ignore: ['DominionCompanion/views/**/*'],
      html: true,
      show: options[:show] || false
    )
  end

  desc 'Release to TestFlight'
  lane :beta_release do
    increment_build_number
    build(release: true)
    upload_to_testflight(
      beta_app_review_info: {
        contact_email: "dominioncompanion@gmail.com",
        contact_first_name: "Harris",
        contact_last_name: "Borawski",
        contact_phone: "8604781448"
      }
    )
    commit_version_bump

  end
end
