# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc 'Unit Tests'
  lane :test do
    scan(
      scheme: 'DominionCompanion',
      output_directory: 'reports',
      code_coverage: true
    )
    slather(
      output_directory: 'reports/coverage',
      html: true,
      scheme: 'DominionCompanion',
      proj: 'DominionCompanion.xcodeproj'
    )
  end
end
