name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ruby Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - name: Build
        run: |
          bundle exec fastlane build
      - name: Test
        run: |
          bundle exec fastlane test
